image: maven:3.9.5-eclipse-temurin-17

stages:
  - verify

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

verify_docs:
  stage: verify
  script:
    - echo "Documentation changes detected"
  only:
    changes:
      - docs/**/*

verify_user_service:
  stage: verify
  script:
    - cd user_service
    - mvn clean verify
  only:
    changes:
      - user_service/**/*

verify_task_service:
  stage: verify
  script:
    - cd task_service
    - mvn clean verify
  only:
    changes:
      - task_service/**/*