@startuml
left to right direction
title Task Tracker - Use Case Diagram

skinparam usecase {
  BackgroundColor<<future>> LightGray
  BorderColor<<future>> Gray
}

actor User

package "User Service" {
  User --> (Create user)
  User --> (Get user by ID)

  (Authorization) <<future>>
  (Roles) <<future>>
}

package "Task Service" {
  User --> (Create task)
  User --> (Get user tasks)
  User --> (Delegate task)

  (Comments) <<future>>
  (Attachments) <<future>>
  (Deadlines) <<future>>
  (Notifications) <<future>>
  (Task priority) <<future>>
}

@enduml
